### ISSUE TITLE
Factories should use JOmniFactory

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#1176]
Several factories need conversion from JChainMultifactory to JOmniFactory:
- [x] #1312
  - [x] TrackerMeasurementFromHits #1168 
  - [x] TrackerHitCollector #1282
  - [x] ChargedParticleSelector #1217 
- [x] factories that don't produce podio collections require the use of the Output syntax in JOmniFactory,
  - [x] CKFTracking writes ActsExamples::Trajectories and ActsExamples::ConstTrackContainer #1168 
  - [x] RichTrack reads ActsExamples::Trajectories and ActsExamples::ConstTrackContainer #1395
  - [x] TrackPropagation reads ActsExamples::Trajectories #1317
  - [x] TrackProjector reads ActsExamples::Trajectories #1168 
  - [x] IterativeVertexFinder reads ActsExamples::Trajectories #1168 
- [x] factories that try to be too clever and do stuff that should be in the algorithm,
  - [x] GeneratedJets passes a vector of Lorentz vectors to the algorithm: being worked on in #1067
  - [x] ReconstructedJets passes a vector of Lorentz vectors to the algorithm: being worked on in #1067
  - [x] PhotoMultiplierHitDigi works differently depending on the name of the plugin in #1177
  - [x] TrackPropagation creates lists of surfaces to propagate to #1317
  - [x] ParticlesWithPID #1178
  - [x] IrtCherenkovParticleID #1418 
- [x] 'variadic' factories that accept arbitrary vectors of input tags and collate them before passing to the algorithm,
  - [x] MatchClusters https://github.com/eic/EICrecon/pull/1314
  - [x] MergeTrack https://github.com/eic/EICrecon/pull/1313
  - [x] ReconstructedElectrons #1209
  - [x] TrackerHitCollector #1282
  - [x] MergeCherenkovParticleID #1419
