### ISSUE TITLE
Summary on logging for EICrecon

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#130]
A meta TODO for logging related issues

- [x] [Consolidate ACTS logging](https://github.com/eic/EICrecon/issues/131)
- [x] [Control global log level through log service](https://github.com/eic/EICrecon/issues/132)
- [x] [Coherent DD4Hep logging](https://github.com/eic/EICrecon/issues/133)
