### ISSUE TITLE
SimQA blocker: all algorithms need verification of digitization and reconstruction options

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#214]
In the 'porting' of algorithms from juggler to EICrecon, only the default values in the algorithm source code were copied over. A lot of these values where overridden in the options files, or pulled from json artifacts stored with the geometry. This is an oversight that must be addressed and verified before any simQA production can start.

This master issue serves to keep the overview of what has been reviewed.

**Please check box only when signing off with @ github handle next to the item.**

- [x] Tracking
  - [x] Have digitization settings from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [x] vertex barrel
    - [x] silicon barrel
    - [x] silicon disks
    - [x] mpgd inner
    - [x] mpgd dirc
    - [x] tof forward
    - [x] tof backward
    - [x] tof barrel
  - [x] Have tracking algorithm parameters (chi2 cuttof) from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [ ] ~~track finding~~
- [ ] PID
- [ ] Calorimetry
  - [ ] Have digitization settings from https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json been ported and verified?
    - [x] ecal forward #205 
    - [x] ecal forward insert #204
    - [x] ecal backward (Carlos e-mail)
    - [x] ecal barrel sciglass
    - [x] ecal barrel imaging   PR #253
    - [x] ecal barrel scfi   PR #253
    - [ ] hcal forward
    - [x] hcal forward insert #202
    - [ ] hcal backward
    - [x] hcal_barrel #233
  - [ ] Have threshold, sampling fractions, and resolutions from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [x] ecal forward #205 
    - [x] ecal forward insert #204
    - [x] ecal backward
    - [x] ecal barrel sciglass
    - [x] ecal barrel imaging   PR #253
    - [x] ecal barrel scfi   PR #253
    - [ ] hcal forward
    - [x] hcal forward insert #202
    - [ ] hcal backward
    - [x] hcal barrel #233
  - [ ] Have clustering algorithm parameters from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [x] ecal forward
    - [ ] ecal forward insert
    - [x] ecal backward
    - [ ] ecal barrel sciglass
    - [ ] ecal barrel imaging   PR #253
    - [ ] ecal barrel scfi   PR #253
    - [ ] hcal forward
    - [ ] hcal forward insert
    - [ ] hcal backward
    - [X] hcal barrel
- [ ] Far forward
  - [ ] Have digitization settings from https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json been ported and verified?
    - [x] B0 ecal #213 
    - [ ] ZDC ecal
    - [ ] Roman Pots (@DraTeots can you take care of roman pots digitization, since closest to a tracker detector?)
- [ ] Far backward

**Comment by DraTeots** [comment]
Correct. Working on it.

**Comment by DraTeots** [comment]
Could you please add TOF to the list also @wdconinc

**Comment by DraTeots** [comment]
We communicated on how to handle this issue. The one of the main issues here is that currently it is very inconvenient to set default values for users (who are not familiar with the code). This will change in future, but as of today - it is scattered around the app. To solve this issue in a more convenient way for users we decided this plan: 

1. We put all the existing flags with default value and create "the monster" launch flags list with all the default parameters. 
2. Users/developers can go through this list and set default parameters fulfilling the issue
3. After this is done and "the monster" launch flags produce satisfying results, we(developers) set those default parameters for users convenients
4. In not distant future we will change how such things are set and it will be convenient (many things are solved by calibration DB)

**Comment by wdconinc** [comment]
Where is that list? We start production on Monday...

**Comment by DraTeots** [comment]
## 1

[There is a file **reco_flags.py** with all EICrecon reconstruction parameters and their values ](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/reco_flags.py)

**This is a single file, that experts can inspect and create PRs with changes if needed**

Initially the file was created automatically. Then manually checked to correspond to physcics_benchmars/reconstruction.py. All parameters values, which descriptions, starts with '*" where manually adjusted from calibrations or reconscrution.py. 


## 2 

There is a [launch_script.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/launch_script.py) file that is generated from [reco_flags.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/reco_flags.py). run launch_script.py to run eicrecon with all those flags: 

```bash
# Run EICrecon with all those parameters
python3 launch_script.py input_file.edm4hep.root   output_file_name_no_extension

# option with number of events: 
python3 launch_script.py input_file.edm4hep.root   output_file_name_no_extension --nevents=100
```

When  [reco_flags.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/reco_flags.py) is modified, a [launch_script.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/launch_script.py) should be regenerated with [gen_launch_script.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/gen_launch_script.py)

**More documentation in #226**

## 3

So here is a list of subsystem that I have manually checked (which doesn't mean everything is correct): 

- [ ] Tracking
  - [ ] Have digitization settings from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [ ] vertex barrel
    - [ ] silicon barrel
    - [ ] silicon disks
    - [ ] mpgd inner
    - [ ] mpgd dirc
    - [x] tof forward
    - [x] tof backward
    - [x] tof barrel
  - [ ] Have tracking algorithm parameters (chi2 cuttof) from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [ ] track finding
- [ ] PID
- [ ] Calorimetry
  - [ ] Have digitization settings from https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json been ported and verified?
    - [ ] ecal forward #205 
    - [ ] ecal forward insert #204
    - [ ] ecal backward
    - [ ] ecal barrel sciglass
    - [ ] ecal barrel imaging
    - [ ] ecal barrel scfi
    - [ ] hcal forward
    - [x] hcal forward insert #202
    - [ ] hcal backward
    - [ ] hcal barrel
  - [ ] Have threshold, sampling fractions, and resolutions from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [ ] ecal forward #205 
    - [ ] ecal forward insert #204
    - [ ] ecal backward
    - [ ] ecal barrel sciglass
    - [ ] ecal barrel imaging
    - [ ] ecal barrel scfi
    - [ ] hcal forward
    - [ ] hcal forward insert #202
    - [ ] hcal backward
    - [ ] hcal barrel
  - [ ] Have clustering algorithm parameters from https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py been ported and verified?
    - [ ] ecal forward
    - [ ] ecal forward insert
    - [ ] ecal backward
    - [ ] ecal barrel sciglass
    - [ ] ecal barrel imaging
    - [ ] ecal barrel scfi
    - [ ] hcal forward
    - [ ] hcal forward insert
    - [ ] hcal backward
    - [ ] hcal barrel
- [ ] Far forward
  - [ ] Have digitization settings from https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json been ported and verified?
    - [ ] B0 ecal #213 
    - [ ] B0 hcal
- [ ] Far backward

**Comment by DraTeots** [comment]
Made [**reco_flags.py**](https://github.com/eic/EICrecon/blob/main/src/tools/default_flags_table/reco_flags.py) runnable. 

So one can now:

```bash
cd EICrecon/src/tools/default_flags_table/
python3 reco_flags.py -n 1000 input.edm4hep.root output_no_ext
```

Also when EICrecon builds it copies reco_flags.py as run_eicrecon_reco_flags.py. So if the output bin directory is in PATH one can do:

```bash

run_eicrecon_reco_flags.py -n 1000 input.edm4hep.root output_no_ext
```

**Comment by ajentsch** [comment]
I am very confused by the FF items. The link to the JSON file doesn't contain anything related to the FF detectors, so that checkbox doesn't make sense. I am following up on the B0ECal, but it is just a PbWO4, so the calibration information (for now) can be the same as the electron endcap. Otherwise, we just need the B0ECalHits to be digitized. 

Lastly, there is no B0HCal, so I think that was a copy/paste mistake.

**Comment by mariakzurek** [comment]
Just to follow up after our office hour discussion. The digitization and reconstruction parameters for SciFi/Pb and Si layers are not included in https://github.com/eic/EICrecon/blob/main/src/tools/default_flags_table/reco_flags.py (so I cannot check it). The sampling fraction for SciFi/Pb should be ~0.1255 (if we don't plan to read it dynamically from detector benchmarks calibration file).

The digitization and reco parameters as implemented in https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json and https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py are ok to use in this production.

**Comment by DraTeots** [comment]
A summary from @veprbl after office hours today: 

During Today's office hours we've discussed validation of the reconstruction parameters in EICrecon (https://github.com/eic/EICrecon/issues/214). The detector experts have to be involved in this.

- For the current campaign, the parameters to be used are collected in https://github.com/eic/EICrecon/blob/main/src/tools/default_flags_table/reco_flags.py . Please check those.
- An issue to separate parameters for SciGlass and Imaging barrel ecal's have been filed https://github.com/eic/EICrecon/issues/247
- An unexpected 0.10856976476514045 sampling fraction was discovered. It is not appropriate for neither the SciGlass nor the Imaging calorimeters. That is to be updated via https://github.com/eic/EICrecon/pull/246 at some point.
- A question (https://github.com/eic/EICrecon/issues/249) have been raised by @Maria Żurek regarding whether the same sampling fraction is applied twice in reconstruction and clustering stages.
- If any of the parameters needs to be updated, please submit pull requests updating both reco_flags.py and the defaults for the respective detector in https://github.com/eic/EICrecon/tree/main/src/detectors
- Dmitry gave some nice explanations regarding difference between how Gaudi and JANA2 are managing the data flow connections between the different algorithms: https://docs.google.com/presentation/d/141mjFaO2FU2vZYqiuqtM_gxM_KoKV22ManRPiAz-KNA/edit#slide=id.g14481abc5b2_0_73
- There is a good value in having "EICrecon office hours", or, perhaps, having those combined with DD4hep office hours.

Thanks for taking those notes!

**Comment by DraTeots** [comment]
@wdconinc please, remove "track finding" from tracking in the top list

**Comment by DraTeots** [comment]
Done with reco_flags.py
