### ISSUE TITLE
Workflow for users and SimQA on default flags and values

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#226]
relates #214

- [x] Users should have a single place to fix flags
- [x] SimQA and other should have a way to run those flags to produce validation results
- [x] EICrecon devs should have tools to see what values in code differ from a single place for flags

**Comment by DraTeots** [comment]
## 1

[There is a file with all EICrecon reconstruction parameters and their values - reco_flags.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/reco_flags.py)

This is a single file, that experts can inspect and create PRs with changes if needed. 

Initially the file was created automatically with 'dump_flags' plugin, then EPIC detector calibrations were applied and then I manually checked all values from Gaudi/Juggler physcics_benchmars reconstruction.py. So now it is a kind of parameters database. All parameters values, which descriptions, starts with '*" where manually adjusted from calibrations or reconscrution.py. 

## 2 

There is a [launch_script.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/launch_script.py) file that is generated from [reco_flags.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/reco_flags.py). run launch_script.py to run eicrecon with all those flags: 

```bash
# Run EICrecon with all those parameters
python3 launch_script.py input_file.edm4hep.root   output_file_name_no_extension

# option with number of events: 
python3 launch_script.py input_file.edm4hep.root   output_file_name_no_extension --nevents=100
```

When  [reco_flags.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/reco_flags.py) is modified, a [launch_script.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/launch_script.py) should be regenerated with [gen_launch_script.py](https://github.com/eic/EICrecon/blob/main/src/tools/default_values_table/gen_launch_script.py)

```bash
# run where reco_flags.py is located
# now it is EICrecon/src/tools/default_values_table/
python3 gen_launch_script.py
```

TODO: 

1. Put CI to generate everything 
2. Make an option not generate launch_script.py (why it is generated at all? To have an ability to check evaluated values that contained units and compare files, etc) 

## 3

To help developers put those flags back into EICrecon and get rid of reco_flags.py we can generate current default parameters from EICrecon and identify what values are different and what fields exists/absent. 

As we have dump_flags plugin we can generate such info on fly. @sqrd-max started to make a dynamic table of flags for it. It will fully appear in 1-2 days. 

https://eic.github.io/EICrecon/#/table_flags/flags

## TODO

Large TODO is to put everything that to CI

**Comment by DraTeots** [comment]
Updates on how it is done is needed

**Comment by DraTeots** [comment]
Made [**reco_flags.py**](https://github.com/eic/EICrecon/blob/main/src/tools/default_flags_table/reco_flags.py) runnable. 

So one can change values in reco_flags.py now and run EICrecon:

```bash
cd EICrecon/src/tools/default_flags_table/
python3 reco_flags.py -n 1000 input.edm4hep.root output_no_ext
```

Also when EICrecon builds it copies reco_flags.py as run_eicrecon_reco_flags.py. So if the output bin directory is in PATH one can do:

```bash

run_eicrecon_reco_flags.py -n 1000 input.edm4hep.root output_no_ext
```

**Comment by sqrd-max** [comment]
generate current default parameters from EICrecon and identify what values are different and what fields exists/absent.
