### ISSUE TITLE
ACTS in JANA2

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#54]
Implement ACTS in JANA2 so we have charged particle tracking.

**Comment by DraTeots** [comment]
To solve the issue, the next steps are to be done: 

- [ ] [Update ACTS to v20](#81)
- [ ] [Add tracking detectors plugins for central region](#82)
- [ ] [Refactor algorithms library and make a space for global algorithms](#83)
- [ ] [Improved tracking testing](https://github.com/eic/EICrecon/issues/84)

**Comment by faustus123** [comment]
Tracking is now working using acts.
